# Site settings
title: Extempra
email: info@extempra.com
description: "Interactive Communications Training - Speak with authenticity, confidence and eloquence."
baseurl: ""
url: "http://xeniatay.com/extempra"

# Build settings
markdown: kramdown
permalink: pretty
