# Site settings
title: Extempra
email: info@extempra.com
description: "Interactive Communications Training - Speak with authenticity, confidence and eloquence."
baseurl: "http://xeniatay.com/extempra/_site"

# Build settings
markdown: kramdown
permalink: pretty
